export const BASKET_ADD_PRODUCT = 'BASKET_ADD_PRODUCT';
export const BASKET_REMOVE_PRODUCT = 'BASKET_REMOVE_PRODUCT';
export const BASKET_TOGGLE = 'BASKET_TOGGLE';
export const BASKET_REMOVE_ITEM_PRODUCT = 'BASKET_REMOVE_ITEM_PRODUCT';
export const GET_ID_SINGLE_PRODUCT = 'GET_ID_SINGLE_PRODUCT';